### ISSUE TITLE
pressStyle not working expo

### ISSUE THREAD

**Issue by andrewchester1** [tamagui/tamagui#1827]
### Current Behavior

pressStyle is not working for any Tamagui components in react-native expo app. The onPress still works, but the pressStyle is not applied to the component.

### Expected Behavior

When the Tamagui Component is pressed, the pressStyle should be applied to the Component

### Tamagui Version

```markdown
"@tamagui/animations-react-native": "^1.76.0",
"@tamagui/babel-plugin": "^1.76.0",
"@tamagui/config": "^1.76.0",
"@tamagui/constants": "^1.76.0",
"@tamagui/font-inter": "^1.76.0",
"@tamagui/lucide-icons": "^1.76.0",
"@tamagui/react-native-media-driver": "^1.76.0",
"@tamagui/shorthands": "^1.76.0",
"@tamagui/themes": "^1.76.0",
"tamagui": "^1.76.0",
```

### Platform (Web, iOS, Android)

```markdown
iOS and Android
```

### Reproduction

```markdown
https://github.com/andrewchester1/press-style-bug
```

### System Info

```markdown
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 16.39 GB / 31.85 GB
  Binaries:
    Node: 19.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.23.2
    @config-plugins/react-native-ble-plx: ^7.0.0 => 7.0.0
    @expo/config-plugins: ~7.2.2 => 7.2.5
    @gorhom/bottom-sheet: 4.4.7 => 4.4.7
    @hookform/resolvers: ^3.1.0 => 3.3.2
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2
    @react-native-community/datetimepicker: 7.2.0 => 7.2.0
    @react-navigation/bottom-tabs: 6.5.8 => 6.5.8
    @react-navigation/drawer: 6.6.6 => 6.6.6
    @react-navigation/elements: 1.3.3 => 1.3.3
    @react-navigation/material-bottom-tabs: 6.2.1 => 6.2.1
    @react-navigation/material-top-tabs: 6.6.3 => 6.6.3
    @react-navigation/native: 6.1.8 => 6.1.8
    @react-navigation/native-stack: 6.9.13 => 6.9.13
    @react-navigation/stack: 6.3.17 => 6.3.17
    @shopify/flash-list: 1.4.3 => 1.4.3
    @stripe/stripe-react-native: 0.28.0 => 0.28.0
    @stripe/stripe-terminal-react-native: 0.0.1-beta.12 => 0.0.1-beta.12
    @tamagui/animations-react-native: ^1.76.0 => 1.76.0
    @tamagui/babel-plugin: ^1.76.0 => 1.76.0
    @tamagui/config: ^1.76.0 => 1.76.0
    @tamagui/constants: ^1.76.0 => 1.76.0
    @tamagui/font-inter: ^1.76.0 => 1.76.0
    @tamagui/lucide-icons: ^1.76.0 => 1.76.0
    @tamagui/react-native-media-driver: ^1.76.0 => 1.76.0
    @tamagui/shorthands: ^1.76.0 => 1.76.0
    @tamagui/themes: ^1.76.0 => 1.76.0
    @tanstack/react-query: ^4.24.10 => 4.36.1
    @types/node: ^20.8.10 => 20.8.10
    @types/react-native: ^0.72.2 => 0.72.5
    @typescript-eslint/eslint-plugin: ^5.5.0 => 5.62.0
    @typescript-eslint/parser: ^5.5.0 => 5.62.0
    axios: ^0.25.0 => 0.25.0
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4
    dotenv: 10.0.0 => 10.0.0
    eslint: ^8.52.0 => 8.53.0
    eslint-config-universe: ^12.0.0 => 12.0.0
    eslint-plugin-react: ^7.27.1 => 7.33.2
    eslint-plugin-react-native: ^4.1.0 => 4.1.0
    expo: 49.0.9 => 49.0.9
    expo-application: ~5.3.0 => 5.3.1
    expo-build-properties: ~0.8.3 => 0.8.3
    expo-camera: ~13.4.4 => 13.4.4
    expo-constants: ~14.4.2 => 14.4.2
    expo-crypto: ~12.4.1 => 12.4.1
    expo-file-system: ~15.4.4 => 15.4.4
    expo-font: ~11.4.0 => 11.4.0
    expo-image: ~1.3.4 => 1.3.5
    expo-image-picker: ~14.3.2 => 14.3.2
    expo-linear-gradient: ~12.3.0 => 12.3.0
    expo-linking: ~5.0.2 => 5.0.2
    expo-local-authentication: ~13.4.1 => 13.4.1
    expo-location: ~16.1.0 => 16.1.0
    expo-network: ~5.4.0 => 5.4.0
    expo-notifications: ~0.20.1 => 0.20.1
    expo-permissions: ~14.2.1 => 14.2.1
    expo-secure-store: ~12.3.1 => 12.3.1
    expo-sms: ~11.4.0 => 11.4.0
    expo-splash-screen: ~0.20.5 => 0.20.5
    expo-status-bar: ~1.6.0 => 1.6.0
    expo-store-review: ~6.4.0 => 6.4.0
    expo-system-ui: ~2.4.0 => 2.4.0
    expo-updates: ~0.18.17 => 0.18.17
    expo-web-browser: ~12.3.2 => 12.3.2
    lottie-react-native: 5.1.6 => 5.1.6
    moment: ^2.29.1 => 2.29.4
    patch-package: ^8.0.0 => 8.0.0
    postinstall-postinstall: ^2.1.0 => 2.1.0
    prettier: ^3.0.3 => 3.0.3
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-hook-form: ^7.43.9 => 7.47.0
    react-native: 0.72.6 => 0.72.6
    react-native-animated-pagination-dot: ^0.4.0 => 0.4.0
    react-native-ble-plx: ^2.0.3 => 2.0.3
    react-native-calendar-strip: ^2.2.6 => 2.2.6
    react-native-chart-kit: ^6.11.0 => 6.12.0
    react-native-dotenv: ^3.3.1 => 3.4.9
    react-native-draggable-flatlist: ^4.0.1 => 4.0.1
    react-native-gesture-handler: ~2.12.0 => 2.12.1
    react-native-gifted-charts: 1.3.16 => 1.3.16
    react-native-image-zoom-viewer: ^3.0.1 => 3.0.1
    react-native-linear-gradient: ^2.8.3 => 2.8.3
    react-native-maps: 1.7.1 => 1.7.1
    react-native-modal-datetime-picker: ^15.0.1 => 15.0.1
    react-native-pager-view: 6.2.0 => 6.2.0
    react-native-reanimated: ~3.3.0 => 3.3.0
    react-native-reanimated-carousel: ^3.5.1 => 3.5.1
    react-native-safe-area-context: 4.6.3 => 4.6.3
    react-native-screens: ~3.22.0 => 3.22.1
    react-native-svg: 13.9.0 => 13.9.0
    react-native-tab-view: 3.5.2 => 3.5.2
    react-native-ui-lib: ^7.9.1 => 7.9.1
    react-native-web: ~0.19.6 => 0.19.9
    recoil: ^0.7.7 => 0.7.7
    tamagui: ^1.76.0 => 1.76.0
    ts-node: ^10.9.1 => 10.9.1
    typescript: ^5.1.3 => 5.2.2
    zod: ^3.21.4 => 3.22.4
```

**Comment by andrewchester1** [comment]
I have spent way too many hours trying to reproduce this in another project, but I was finally able to reproduce the bug. The pressStyle was working on tamagui 1.68.5, after upgrading to 1.76.0, the pressStyle stopped working. I have gone through all the Tamagui expo config documentation, to see if the expo configuration has changed, but I am still unable to resolve this issue. Any help would be greatly appreciated!

**Comment by natew** [comment]
answered in discord but it is working, your config was messed up

**Comment by andrewchester1** [comment]
`process.env.TAMAGUI_TARGET = "native";

module.exports = function (api) {
	api.cache(true);
	return {
		presets: ["babel-preset-expo"],
		plugins: [
			[
				"module:react-native-dotenv",
				{
					moduleName: "@env",
					path: ".env",
					blacklist: null,
					whitelist: null,
					safe: false,
					allowUndefined: true,
				},
			],
			[
				"transform-inline-environment-variables",
			],
			// NOTE: this is only necessary if you are using reanimated for animations
			"react-native-reanimated/plugin",
		],
	};
};`

**Comment by andrewchester1** [comment]
Changing the babel.config.js to the comment above fixed the pressStyle issue for me!

**Comment by TomasSestak** [comment]
adding process.env.TAMAGUI_TARGET = 'native' helped me aswell, but on fresh project it works even without this line...weird.

but thanks for the fix
