### ISSUE TITLE
Server Error: Cannot find module '@tamagui/linear-gradient/dist/esm/LinearGradient'

### ISSUE THREAD

**Issue by ZelimDamian** [tamagui/tamagui#1074]
### Current Behavior

The LinearGradient component imported with 
```tsx
import { LinearGradient } from 'tamagui/linear-gradient'
```

and used as

```tsx
<LinearGradient
    start={[0, 0]}
    end={[0, 1]}
    fullscreen
    colors={['$backgroundTransparent', '$background']}
    borderRadius="$4"
 />
```

works fine as client rendered component but fails when rendered on the server with Next.js SSR with the following error:

```
Server Error
Error: Cannot find module '/project/sandbox/node_modules/@tamagui/linear-gradient/dist/esm/LinearGradient' imported from /project/sandbox/node_modules/@tamagui/linear-gradient/dist/esm/index.mjs

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
new NodeError
node:internal/errors (387:5)
finalizeResolution
node:internal/modules/esm/resolve (429:11)
moduleResolve
node:internal/modules/esm/resolve (1006:10)
defaultResolve
node:internal/modules/esm/resolve (1214:11)
nextResolve
node:internal/modules/esm/loader (165:28)
ESMLoader.resolve
node:internal/modules/esm/loader (844:30)
ESMLoader.getModuleJob
node:internal/modules/esm/loader (431:18)
ModuleWrap.<anonymous>
node:internal/modules/esm/module_job (76:40)
link
node:internal/modules/esm/module_job (75:36)
```

### Expected Behavior

LinearGradient component should work when rendered on the server with Next.js SSR. When the ```user``` page is rendered on with SSR.

### Tamagui Version

```markdown
v1.15.15 (probably before) and v1.21.4
```

### Reproduction

EDIT: after upgrading Codesandbox to 1.22 the error shows up immediately without the need perform the steps below. This happened somewhere between v1.21.4 and v1.22.4

STEPS:
1. [Open the CodeSandbox link](https://codesandbox.io/p/sandbox/festive-ives-3x713r?file=%2FREADME.md)
2. Run `npm run web`
3. [Click on "Link to user"](https://i.imgur.com/Sd7x3IE.png)
4. [Works fine](https://i.imgur.com/PvNGOYo.png)
5. [Refresh the page](https://i.imgur.com/2MqMsFx.png)
6. [Observe the error](https://i.imgur.com/VS4InWg.png)

### System Info

```markdown
Reproduces in Sandbox.io

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 43.36 MB / 1.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.8.3 => 1.9.3 
    typescript: ^4.7.4 => 4.9.5 ```
```

**Comment by tamagutchi** [comment]
Having the same issue. Any updates?

**Comment by tamagutchi** [comment]
@ZelimDamian I managed to get it working by importing from `@tamagui/linear-gradient` instead of `tamagui/linear-gradient`

**Comment by ZelimDamian** [comment]
> @ZelimDamian I managed to get it working by importing from `@tamagui/linear-gradient` instead of `tamagui/linear-gradient`

You are right! Works fine after your suggested change.
I copied the select/gradient code from [the official docs](https://tamagui.dev/docs/components/linear-gradient/1.0.0) which doesn't the scoped name. Thanks!
